stages:
    - build
    - push

variables:
    IMAGE_NAME: $CI_PROJECT_PATH
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build:
    stage: build

    image: docker:latest

    services:
        - docker:dind

    variables:
        DOCKER_TLS_CERTDIR: "/certs"

    before_script:
        - apt upgrade && apt update
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWD

    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG --file Dockerfile.test .

push:
    stage: push

    image: docker:latest

    services:
        - docker:dind

    script:
        - docker push $IMAGE_NAME:$IMAGE_TAG
