stages:
    - build
    - deploy

variables:
    IMAGE_NAME: $CI_PROJECT_PATH
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build:
    stage: build

    image: docker:latest

    services:
        - docker:dind

    variables:
        DOCKER_TLS_CERTDIR: "/certs"

    before_script:
        - echo $DOCKER_PASSWD | docker login -u $DOCKER_USER --password-stdin

    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG --file $DOCKER_FILE .
        - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
    stage: deploy

    image: alpine:latest

    before_script:
        - chmod 400 $SSH_KEY

    script:
        - ssh -i $SSH_KEY $USER_NAME@$HOST_NAME "$DEPLOY_SCRIPT $DOCKER_USER $DOCKER_PASSWD $IMAGE_NAME"
