services:
    website:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
            no_cache: true

        ports:
            - 4321:4321

        env_file: .env.development
