FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json .

FROM base AS build 

RUN npm ci

COPY . .

RUN npx prisma generate

RUN npm run build

FROM node:20-alpine AS runtime

LABEL maintainer="Anav Chand <me@anav.dev>"

WORKDIR /app

COPY --from=build /app/node_modules/.prisma ./node_modules/.prisma

COPY --from=build /app/dist ./dist

EXPOSE 4321

CMD ["node", "./dist/server/entry.mjs"]