# Fully static build served from Nginx

FROM node:20 AS build

RUN curl -fsSL https://d2lang.com/install.sh | sh -s --

WORKDIR /app
    
COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:alpine AS runtime

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
