export const tagToSlug: Record<string, string> = {
    AI: "ai",
    API: "api",
    Architecture: "architecture",
    Astro: "astro",
    "C++": "c-plus-plus",
    CLI: "cli",
    Cloud: "cloud",
    Database: "database",
    DevOps: "devops",
    DNS: "dns",
    Docker: "docker",
    Drizzle: "drizzle",
    Electron: "electron",
    Expo: "expo",
    Express: "express",
    Git: "git",
    "HTML/CSS": "html-css",
    Homelab: "homelab",
    JavaScript: "javascript",
    Kafka: "kafka",
    Mobile: "mobile",
    MongoDB: "mongodb",
    "Next.js": "next-js",
    "Node.js": "node-js",
    ORM: "orm",
    PostgreSQL: "postgresql",
    Prisma: "prisma",
    Python: "python",
    React: "react",
    "React Native": "react-native",
    "Real-time": "real-time",
    Redis: "redis",
    Render: "render",
    Security: "security",
    Stripe: "stripe",
    Supabase: "supabase",
    Svelte: "svelte",
    "Tailwind CSS": "tailwind-css",
    TypeScript: "typescript",
    University: "university",
    Vercel: "vercel"
};

export const slugToTag: Record<string, string> = Object.fromEntries(
    Object.entries(tagToSlug).map(([tag, slug]) => [slug, tag])
);
